### ISSUE TITLE
Video preview not working in Sanity v3

### ISSUE THREAD

**Issue by mravand** [sanity-io/sanity-plugin-cloudinary#19]
Not getting preview of video anymore :(

<img width="684" alt="image" src="https://user-images.githubusercontent.com/111656058/212017498-e28b6c3a-589e-4da6-a29d-7f3201db584b.png">

**Comment by lanelps** [comment]
I'm also having this issue

**Comment by cdedreuille** [comment]
Yes, same for me. That's all the errors I'm experimenting right now.
<img width="1327" alt="CleanShot 2023-02-16 at 10 41 27@2x" src="https://user-images.githubusercontent.com/1540635/219342759-b1cf93fe-2740-494c-98bf-92332b955838.png">

**Comment by snorrees** [comment]
Just released a a quickfix for the videoplayer and preview: [1.0.2](https://github.com/sanity-io/sanity-plugin-cloudinary/releases/tag/v1.0.2)
