### ISSUE TITLE
Can't add multiple assets at once in Sanity V3

### ISSUE THREAD

**Issue by duanecilliers** [sanity-io/sanity-plugin-cloudinary#20]
According to the [README](https://github.com/sanity-io/sanity-plugin-cloudinary#in-arrays) you can add multiple assets at once if used in an array.

This isn't the case in V3. I looked at the code and noticed it isn't wired up.

![Screenshot 2023-02-23 at 15 00 18](https://user-images.githubusercontent.com/1135407/220913537-4ebe8ac8-17a6-4855-b6be-ae0ded9c2366.png)

I will dig into the v2 => v3 migration docs and see if I can create a PR for this.

In the meantime it's probably a good idea to update the README to avoid confusion.

**Comment by erikaaasberg** [comment]
👆😅 Having the same issue!

**Comment by duanecilliers** [comment]
My colleague and I are looking into it, there should be a PR for this soon.

**Comment by duanecilliers** [comment]
Hey @snorrees. Thank you, this resolves the problem 🙏🏻
