### ISSUE TITLE
Type is missing title. Warning in the studio in dev mode.

### ISSUE THREAD

**Issue by badantlerday** [sanity-io/sanity-plugin-cloudinary#40]
Using latest version of plugin and sanity.
I'm not sure were the problem is if it's my installation or the plugin.

<img width="944" alt="image" src="https://github.com/sanity-io/sanity-plugin-cloudinary/assets/6713806/9483f59e-3f53-4d2c-a9e1-866bc1a0276e">

**Comment by cerpow** [comment]
+1

**Comment by jmsherry** [comment]
+1

**Comment by viarms** [comment]
+1

**Comment by henrybabbage** [comment]
+1

**Comment by olbrown** [comment]
+1

**Comment by badantlerday** [comment]
Ok seems like the waring now is fixed thanks to an update to Sanity Studio.
In the version 3.14.4 I'm not getting the warning anymore.
https://www.sanity.io/changelog#change-07656110-93a2-4831-bd04-6616f12bbf1a

> Removes warning about missing titles for schema types (titles are automatically created based on schema type name - a title is only necessary if the automatic name is incorrect/inaccurate)
