### ISSUE TITLE
TypeError: Cannot destructure property 'media' of 'theme.sanity' as it is undefined.

### ISSUE THREAD

**Issue by DRITE** [sanity-io/sanity-plugin-cloudinary#42]
Hello there!

I got an error `TypeError: Cannot destructure property 'media' of 'theme.sanity' as it is undefined.` when I had attempted to create a field
```typescript
    defineField({
      title: 'Picture from cloudinary',
      name: 'cloudinaryPic',
      type: 'cloudinary.asset',
      description: 'Image from cloudinary',
    })
```
using  `cloudinarySchemaPlugin` from `"sanity-plugin-cloudinary": "1.1.1"`
![image](https://github.com/sanity-io/sanity-plugin-cloudinary/assets/1095379/922a6451-d706-4e35-996d-5ca6e33ce760)

## My environment
```
"sanity": "3",
"sanity-plugin-cloudinary": "^1.1.1",
"react": "18.2.0",
"react-dom": "18.2.0",
```

## Some thoughts on the error
* `sanity-plugin-cloudinary` has `@sanity/ui` as its dependency
* `@sanity/ui` [declares `theme` as a required](https://github.com/sanity-io/ui/blob/main/src/styles/types.ts#L7) prop for [`responsiveStackSpaceStyle`](https://github.com/sanity-io/ui/blob/main/src/primitives/stack/styles.ts#L23) function
* But `sanity-plugin-cloudinary` doesn't provide the `theme` neither [here](https://github.com/sanity-io/sanity-plugin-cloudinary/blob/main/src/components/asset-source/CloudinaryAssetSource.tsx#L141) nor [there](https://github.com/sanity-io/sanity-plugin-cloudinary/blob/main/src/components/WidgetInput.tsx#L26)
* Hense we got the error on [this](https://github.com/sanity-io/ui/blob/main/src/primitives/stack/styles.ts#L27) string (see a  picture above)

**Comment by DRITE** [comment]
Works with the following versions:

```
"sanity-plugin-cloudinary": "~1.1.1",
"sanity": "3.14.2",
"@sanity/types": "3.14.2",
"@sanity/vision": "3.14.2",
```

**Comment by bobinska-dev** [comment]
BTW: When these kind of issues arise (conflicts of dependencies), you can just make sure both are installed like this:

npm i <YOUR DEP> --legacy-peer-deps
